### PR TITLE
Refactor to separate UI code from core code

### PR DESCRIPTION
**Pull request by CreatureSurvive**
• refactored the project to separate UI code from the core functionality code.
• slight refactor of the UI code
• switched to SFSafariViewController to remove depreciated warning on openURL:
• added support for URL Schemes i.e App-Installer://Your_Download_Link
• overall easier extensibility

### CODE REVIEW

**Comment by Sn0wCh1ld** [comment]
A new version of App Installer was released. Do you think you could update your code to be compatible with the new version? Sorry for the inconvenience, I appreciate your work.

**Comment by CreatureSurvive** [comment]
I've updated my code to be compatible with the latest update and resolved the conflicts. I'm not sure if you were able to get the share menu working on your end, but it is not working for me so I can't test if the pasteboard option is working in this, though it should.

**Comment by Sn0wCh1ld** [comment]
I'm so sorry, I pushed a bug fix for a crashing issue that simply required a reconnection of a button. If you could just update your Storyboard one more time it would be much appreciated. As long as there isn't any more crashing, your pull request is at the top of my to-do list.

**Comment by CreatureSurvive** [comment]
I think you'll have to manually resolve these conflicts, both yours and my commit remap buttons in the storyboard and for some reason, it won't let me resolve the conflicts from my end. I double checked and my storyboard file works fine in place of yours.

**Comment by nullpixel** [comment]
You can resolve conflicts locally

**Comment by CreatureSurvive** [comment]
@nullpixel care to elaborate a bit? I was able to resolve the last conflict in the browser, but this one says it's to complex. when trying to resolve locally all I know to do is make sure everything is operational and push the commit, but it still conflicts.

**Comment by CreatureSurvive** [comment]
@nullpixel nevermind, I figured it out. I forgot to pull the latest update back into my fork.

**Comment by Sn0wCh1ld** [comment]
Also, I was able to get the share menu working with version 1.0.2.1, but I can't test the new version with your edits, because I don't permanently have access to a 3D Touch capable device.

**Comment by CreatureSurvive** [comment]
I see that it shows up in the shortcut menu now, but it's not working properly. I've never worked with the 3D touch so I'm not very familiar with it.

**Comment by Sn0wCh1ld** [comment]
It only works when it's used at app launch (not from background), because it uses didFinishLaunchingWithOptions and not applicationDidBecomeActive in the AppDelegate.

**Comment by CreatureSurvive** [comment]
turns out they offer performActionForShortcutItem for this reason

**Comment by Sn0wCh1ld** [comment]
Had no idea that existed (I just learned how to do 3D Touch shortcuts yesterday). Nice work!

**Pull request merged**
